In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Connect to the PostgreSQL database
engine = create_engine('postgresql://postgres:123@localhost:5432/group4_project_1')

In [3]:
data = pd.read_csv('/Users/maple/Desktop/5310/train.csv')

In [4]:
print(data.head())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12

  YrSold  SaleType  SaleCondition  SalePrice
0   2008        WD         Normal     208500
1   2007        WD         Normal     181500
2   2008        WD         Normal     223500
3   2006        WD        Abnorml     140000
4   2008        WD         Normal     250000

[5 rows x 81 columns]

In [5]:
# Write to Sale table
sale_data = data[['Id','MoSold','YrSold','SaleType','SaleCondition','SalePrice']]
sale_data.to_sql('Sale', con=engine, if_exists='append', index=False)

# Write to Property table
property_data = data[['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'LotFrontage', 'Street', 'Alley', 'Neighborhood', 'Condition1', 'Condition2']]
property_data.to_sql('Property', con=engine, if_exists='append', index=False)

# Write to Building table
building_data = data[['Id', 'BldgType', 'HouseStyle', 'YearBuilt', 'YearRemodAdd', 'TotRmsAbvGrd', 'Functional']]
building_data.to_sql('Building', con=engine, if_exists='append', index=False)

# Write to Exterior table
exterior_data = data[['Id', 'RoofStyle', 'Fence', 'MasVnrArea']]
exterior_data.to_sql('Exterior', con=engine, if_exists='append', index=False)

# Write to Material table
material_data = data[['Id', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation']]
material_data.to_sql('Material', con=engine, if_exists='append', index=False)

# Write to Basement table
basement_data = data[['Id', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF']]
basement_data.to_sql('Basement', con=engine, if_exists='append', index=False)

# Write to HeatingAirCond table
heatingaircond_data = data[['Id', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical']]
heatingaircond_data.to_sql('HeatingairCond', con=engine, if_exists='append', index=False)

# Write to Floor table
floor_data = data[['Id', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea']]
floor_data.to_sql('Floor', con=engine, if_exists='append', index=False)

# Write to Bathrooms table
bathrooms_data = data[['Id', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath']]
bathrooms_data.to_sql('Bathrooms', con=engine, if_exists='append', index=False)

# Write to Kitchen table
kitchen_data = data[['Id', 'KitchenAbvGr', 'KitchenQual']]
kitchen_data.to_sql('Kitchen', con=engine, if_exists='append', index=False)

# Write to Bedrooms table
bedrooms_data = data[['Id', 'BedroomAbvGr']]
bedrooms_data.to_sql('Bedrooms', con=engine, if_exists='append', index=False)

# Write to Fireplace table
fireplace_data = data[['Id', 'Fireplaces', 'FireplaceQu']]
fireplace_data.to_sql('Fireplace', con=engine, if_exists='append', index=False)

# Write to Garage table
garage_data = data[['Id', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond']]
garage_data.to_sql('Garage', con=engine, if_exists='append', index=False)

# Write to Driveway table
driveway_data = data[['Id', 'PavedDrive']]
driveway_data.to_sql('Driveway', con=engine, if_exists='append', index=False)

# Write to DeckPorch table
deckporch_data = data[['Id', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch']]
deckporch_data.to_sql('Deckporch', con=engine, if_exists='append', index=False)

# Write to Pool table
pool_data = data[['Id', 'PoolArea', 'PoolQC']]
pool_data.to_sql('Pool', con=engine, if_exists='append', index=False)

# Write to Miscellaneous table
misc_data = data[['Id', 'MiscFeature', 'MiscVal']]
misc_data.to_sql('Miscellaneous', con=engine, if_exists='append', index=False)

460

In [8]:
# Querying imported data
conn_string = 'postgresql://postgres:123@localhost:5432/group4_project_1'

engine = create_engine(conn_string)

connection = engine.connect()


tables = ['Sale', 'Property', 'Building', 'Exterior', 'Material', 'Basement', 'HeatingairCond', 'Floor', 'Bathrooms', 'Kitchen', 'Fireplace', 'Garage', 'Driveway', 'Deckporch', 'Pool', 'Miscellaneous']

for table in tables:
    query = f'SELECT * FROM "{table}"'
    result = connection.execute(query).fetchall()
    column_names = result[0].keys() if result else []
    df = pd.DataFrame(result, columns=column_names)
    print(f'--- Data from {table} ---\n')
    print(df)
    print("\n")

--- Data from Sale ---

        Id  MoSold  YrSold SaleType SaleCondition  SalePrice
0        1       2    2008       WD        Normal     208500
1        2       5    2007       WD        Normal     181500
2        3       9    2008       WD        Normal     223500
3        4       2    2006       WD       Abnorml     140000
4        5      12    2008       WD        Normal     250000
...    ...     ...     ...      ...           ...        ...
2915  1456       8    2007       WD        Normal     175000
2916  1457       2    2010       WD        Normal     210000
2917  1458       5    2010       WD        Normal     266500
2918  1459       4    2010       WD        Normal     142125
2919  1460       6    2008       WD        Normal     147500

[2920 rows x 6 columns]


--- Data from Property ---

        Id  MSSubClass MSZoning  LotArea LotShape LandContour Utilities  \
0        1          60       RL     8450      Reg         Lvl    AllPub
1        2          20       RL     9600      Reg         Lvl    AllPub
2        3          60       RL    11250      IR1         Lvl    AllPub
3        4          70       RL     9550      IR1         Lvl    AllPub
4        5          60       RL    14260      IR1         Lvl    AllPub
...    ...         ...      ...      ...      ...         ...       ...
2915  1456          60       RL     7917      Reg         Lvl    AllPub
2916  1457          20       RL    13175      Reg         Lvl    AllPub
2917  1458          70       RL     9042      Reg         Lvl    AllPub
2918  1459          20       RL     9717      Reg         Lvl    AllPub
2919  1460          20       RL     9937      Reg         Lvl    AllPub

     LotConfig LandSlope  LotFrontage Street Alley Neighborhood Condition1  \
0       Inside       Gtl         65.0   Pave  None      CollgCr       Norm
1          FR2       Gtl         80.0   Pave  None      Veenker      Feedr
2       Inside       Gtl         68.0   Pave  None      CollgCr       Norm
3       Corner       Gtl         60.0   Pave  None      Crawfor       Norm
4          FR2       Gtl         84.0   Pave  None      NoRidge       Norm
...        ...       ...          ...    ...   ...          ...        ...
2915    Inside       Gtl         62.0   Pave  None      Gilbert       Norm
2916    Inside       Gtl         85.0   Pave  None       NWAmes       Norm
2917    Inside       Gtl         66.0   Pave  None      Crawfor       Norm
2918    Inside       Gtl         68.0   Pave  None        NAmes       Norm
2919    Inside       Gtl         75.0   Pave  None      Edwards       Norm

     Condition2
0          Norm
1          Norm
2          Norm
3          Norm
4          Norm
...         ...
2915       Norm
2916       Norm
2917       Norm
2918       Norm
2919       Norm

[2920 rows x 15 columns]


--- Data from Building ---

        Id BldgType HouseStyle  YearBuilt  YearRemodAdd  TotRmsAbvGrd  \
0        1     1Fam     2Story       2003          2003             8
1        2     1Fam     1Story       1976          1976             6
2        3     1Fam     2Story       2001          2002             6
3        4     1Fam     2Story       1915          1970             7
4        5     1Fam     2Story       2000          2000             9
...    ...      ...        ...        ...           ...           ...
2915  1456     1Fam     2Story       1999          2000             7
2916  1457     1Fam     1Story       1978          1988             7
2917  1458     1Fam     2Story       1941          2006             9
2918  1459     1Fam     1Story       1950          1996             5
2919  1460     1Fam     1Story       1965          1965             6

     Functional
0           Typ
1           Typ
2           Typ
3           Typ
4           Typ
...         ...
2915        Typ
2916       Min1
2917        Typ
2918        Typ
2919        Typ

[2920 rows x 7 columns]


--- Data from Exterior ---

        Id RoofStyle  Fence  MasVnrArea
0        1     Gable   None       196.0
1        2     Gable   None         0.0
2        3     Gable   None       162.0
3        4     Gable   None         0.0
4        5     Gable   None       350.0
...    ...       ...    ...         ...
2915  1456     Gable   None         0.0
2916  1457     Gable  MnPrv       119.0
2917  1458     Gable  GdPrv         0.0
2918  1459       Hip   None         0.0
2919  1460     Gable   None         0.0

[2920 rows x 4 columns]


--- Data from Material ---

        Id RoofMatl Exterior1st Exterior2nd MasVnrType ExterQual ExterCond  \
0        1  CompShg     VinylSd     VinylSd    BrkFace        Gd        TA
1        2  CompShg     MetalSd     MetalSd       None        TA        TA
2        3  CompShg     VinylSd     VinylSd    BrkFace        Gd        TA
3        4  CompShg     Wd Sdng     Wd Shng       None        TA        TA
4        5  CompShg     VinylSd     VinylSd    BrkFace        Gd        TA
...    ...      ...         ...         ...        ...       ...       ...
2915  1456  CompShg     VinylSd     VinylSd       None        TA        TA
2916  1457  CompShg     Plywood     Plywood      Stone        TA        TA
2917  1458  CompShg     CemntBd     CmentBd       None        Ex        Gd
2918  1459  CompShg     MetalSd     MetalSd       None        TA        TA
2919  1460  CompShg     HdBoard     HdBoard       None        Gd        TA

     Foundation
0         PConc
1        CBlock
2         PConc
3        BrkTil
4         PConc
...         ...
2915      PConc
2916     CBlock
2917      Stone
2918     CBlock
2919     CBlock

[2920 rows x 8 columns]


--- Data from Basement ---

        Id BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1  \
0        1       Gd       TA           No          GLQ         706
1        2       Gd       TA           Gd          ALQ         978
2        3       Gd       TA           Mn          GLQ         486
3        4       TA       Gd           No          ALQ         216
4        5       Gd       TA           Av          GLQ         655
...    ...      ...      ...          ...          ...         ...
2915  1456       Gd       TA           No          Unf           0
2916  1457       Gd       TA           No          ALQ         790
2917  1458       TA       Gd           No          GLQ         275
2918  1459       TA       TA           Mn          GLQ          49
2919  1460       TA       TA           No          BLQ         830

     BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF
0             Unf           0        150          856
1             Unf           0        284         1262
2             Unf           0        434          920
3             Unf           0        540          756
4             Unf           0        490         1145
...           ...         ...        ...          ...
2915          Unf           0        953          953
2916          Rec         163        589         1542
2917          Unf           0        877         1152
2918          Rec        1029          0         1078
2919          LwQ         290        136         1256

[2920 rows x 10 columns]


--- Data from HeatingairCond ---

        Id Heating HeatingQC CentralAir Electrical
0        1    GasA        Ex          Y      SBrkr
1        2    GasA        Ex          Y      SBrkr
2        3    GasA        Ex          Y      SBrkr
3        4    GasA        Gd          Y      SBrkr
4        5    GasA        Ex          Y      SBrkr
...    ...     ...       ...        ...        ...
2915  1456    GasA        Ex          Y      SBrkr
2916  1457    GasA        TA          Y      SBrkr
2917  1458    GasA        Ex          Y      SBrkr
2918  1459    GasA        Gd          Y      FuseA
2919  1460    GasA        Gd          Y      SBrkr

[2920 rows x 5 columns]


--- Data from Floor ---

        Id  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea
0        1       856       854             0       1710
1        2      1262         0             0       1262
2        3       920       866             0       1786
3        4       961       756             0       1717
4        5      1145      1053             0       2198
...    ...       ...       ...           ...        ...
2915  1456       953       694             0       1647
2916  1457      2073         0             0       2073
2917  1458      1188      1152             0       2340
2918  1459      1078         0             0       1078
2919  1460      1256         0             0       1256

[2920 rows x 5 columns]


--- Data from Bathrooms ---

        Id  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath
0        1             1             0         2         1
1        2             0             1         2         0
2        3             1             0         2         1
3        4             1             0         1         0
4        5             1             0         2         1
...    ...           ...           ...       ...       ...
2915  1456             0             0         2         1
2916  1457             1             0         2         0
2917  1458             0             0         2         0
2918  1459             1             0         1         0
2919  1460             1             0         1         1

[2920 rows x 5 columns]


--- Data from Kitchen ---

        Id  KitchenAbvGr KitchenQual
0        1             1          Gd
1        2             1          TA
2        3             1          Gd
3        4             1          Gd
4        5             1          Gd
...    ...           ...         ...
2915  1456             1          TA
2916  1457             1          TA
2917  1458             1          Gd
2918  1459             1          Gd
2919  1460             1          TA

[2920 rows x 3 columns]


--- Data from Fireplace ---

        Id  Fireplaces FireplaceQu
0        1           0        None
1        2           1          TA
2        3           1          TA
3        4           1          Gd
4        5           1          TA
...    ...         ...         ...
2915  1456           1          TA
2916  1457           2          TA
2917  1458           2          Gd
2918  1459           0        None
2919  1460           0        None

[2920 rows x 3 columns]


--- Data from Garage ---

        Id GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea  \
0        1     Attchd       2003.0          RFn           2         548
1        2     Attchd       1976.0          RFn           2         460
2        3     Attchd       2001.0          RFn           2         608
3        4     Detchd       1998.0          Unf           3         642
4        5     Attchd       2000.0          RFn           3         836
...    ...        ...          ...          ...         ...         ...
2915  1456     Attchd       1999.0          RFn           2         460
2916  1457     Attchd       1978.0          Unf           2         500
2917  1458     Attchd       1941.0          RFn           1         252
2918  1459     Attchd       1950.0          Unf           1         240
2919  1460     Attchd       1965.0          Fin           1         276

     GarageQual GarageCond
0            TA         TA
1            TA         TA
2            TA         TA
3            TA         TA
4            TA         TA
...         ...        ...
2915         TA         TA
2916         TA         TA
2917         TA         TA
2918         TA         TA
2919         TA         TA

[2920 rows x 8 columns]


--- Data from Driveway ---

        Id PavedDrive
0        1          Y
1        2          Y
2        3          Y
3        4          Y
4        5          Y
...    ...        ...
2915  1456          Y
2916  1457          Y
2917  1458          Y
2918  1459          Y
2919  1460          Y

[2920 rows x 2 columns]


--- Data from Deckporch ---

        Id  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch
0        1           0           61              0          0            0
1        2         298            0              0          0            0
2        3           0           42              0          0            0
3        4           0           35            272          0            0
4        5         192           84              0          0            0
...    ...         ...          ...            ...        ...          ...
2915  1456           0           40              0          0            0
2916  1457         349            0              0          0            0
2917  1458           0           60              0          0            0
2918  1459         366            0            112          0            0
2919  1460         736           68              0          0            0

[2920 rows x 6 columns]


--- Data from Pool ---

        Id  PoolArea PoolQC
0        1         0   None
1        2         0   None
2        3         0   None
3        4         0   None
4        5         0   None
...    ...       ...    ...
2915  1456         0   None
2916  1457         0   None
2917  1458         0   None
2918  1459         0   None
2919  1460         0   None

[2920 rows x 3 columns]


--- Data from Miscellaneous ---

        Id MiscFeature  MiscVal
0        1        None        0
1        2        None        0
2        3        None        0
3        4        None        0
4        5        None        0
...    ...         ...      ...
2915  1456        None        0
2916  1457        None        0
2917  1458        Shed     2500
2918  1459        None        0
2919  1460        None        0

[2920 rows x 3 columns]

In [9]:
# Query 1: Average Sale Price for Each Neighborhood
query1 = """
SELECT 
    "Neighborhood", 
    AVG("SalePrice") AS AvgSalePrice
FROM 
    "Property" 
JOIN 
    "Sale" ON "Property"."Id" = "Sale"."Id"
GROUP BY 
    "Neighborhood"
ORDER BY 
    AvgSalePrice DESC;
"""
result1 = connection.execute(query1)
df1 = pd.DataFrame(result1.fetchall(), columns=result1.keys())
print("--- Average Sale Price for Each Neighborhood ---\n")
print(df1)
print("\n")

--- Average Sale Price for Each Neighborhood ---

   Neighborhood         avgsaleprice
0       NoRidge  335295.317073170732
1       NridgHt  316270.623376623377
2       StoneBr  310499.000000000000
3        Timber  242247.447368421053
4       Veenker  238772.727272727273
5       Somerst  225379.837209302326
6       ClearCr  212565.428571428571
7       Crawfor  210624.725490196078
8       CollgCr  197965.773333333333
9       Blmngtn  194870.882352941176
10      Gilbert  192854.506329113924
11       NWAmes  189050.068493150685
12      SawyerW  186555.796610169492
13      Mitchel  156270.122448979592
14        NAmes  145847.080000000000
15      NPkVill  142694.444444444444
16        SWISU  142591.360000000000
17      Blueste  137500.000000000000
18       Sawyer  136793.135135135135
19      OldTown  128225.300884955752
20      Edwards  128219.700000000000
21      BrkSide  124834.051724137931
22       BrDale  104493.750000000000
23       IDOTRR  100123.783783783784
24      MeadowV   98576.470588235294

In [10]:
# Query 2: Top 5 Most Expensive Houses
query2 = """
SELECT 
    "SalePrice", 
    "Neighborhood"
FROM 
    "Property"
JOIN 
    "Sale" ON "Property"."Id" = "Sale"."Id"
ORDER BY 
    "SalePrice" DESC
LIMIT 5;
"""
result2 = connection.execute(query2)
df2 = pd.DataFrame(result2.fetchall(), columns=result2.keys())
print("--- Top 5 Most Expensive Houses ---\n")
print(df2)
print("\n")

--- Top 5 Most Expensive Houses ---

   SalePrice Neighborhood
0     755000      NoRidge
1     755000      NoRidge
2     755000      NoRidge
3     755000      NoRidge
4     745000      NoRidge

In [11]:
# Query 3: Property Pricing Trends Over Time
query3 = """
SELECT "YrSold", AVG("SalePrice") AS "Average_Price"
FROM "Sale"
GROUP BY "YrSold"
ORDER BY "YrSold";
"""
result3 = connection.execute(query3)
df3 = pd.DataFrame(result3.fetchall(), columns=result3.keys())
print("--- Property Pricing Trends Over Time ---\n")
print(df3)
print("\n")

--- Property Pricing Trends Over Time ---

   YrSold        Average_Price
0    2006  182549.458598726115
1    2007  186063.151975683891
2    2008  177360.838815789474
3    2009  179432.103550295858
4    2010  177393.674285714286

In [ ]:
connection.close()